services:
  shell:
    image: node:22
    container_name: runestone_shell
    working_dir: /app
    user: "${LOCAL_UID}:${LOCAL_GID}"
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm run dev"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    volumes:
      - ./:/app
  localstack:
    image: localstack/localstack
    container_name: localstack_main
    env_file:
      - .env
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "./.localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DEBUG=0
